version: '3'
services:
  tridoc:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "fuseki"
    volumes:
      - ./blobs:/usr/src/app/blobs
    environment:
      TRIDOC_PWD: "${TRIDOC_PWD}"
  # If you override the command, make sure all required Deno permissions are present (e.g., --allow-write for all needed directories, --allow-read, --allow-net, etc.)
  # Example:
  # command: deno run --allow-net --allow-read=blobs,rdf.ttl --allow-write=blobs,rdf.ttl,/tmp --allow-run --allow-env=TRIDOC_PWD,OCR_LANG src/main.ts
  fuseki:
    image: "linkedsolutions/fuseki"
    environment:
      ADMIN_PASSWORD: "${FUSEKI_PWD:-pw123}"
    volumes:
      - ./fuseki-db:/DB
      - ./config-tdb.ttl:/fuseki/set-up-resources/config-tdb